version: '3.8'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "1000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  solicitudes:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db-data: